api/v1/people/urls.py
from django.urls import path

from api.v1.people.views import TeacherListView, TeacherProfileView, StudentProfileView, StudentCreateView


urlpatterns = [
    path('teacher/', TeacherListView.as_view()),
    path('teacher/<int:pk>/', TeacherProfileView.as_view()),
    path('create-student/', StudentCreateView.as_view()),
    path('student/<int:pk>/', StudentProfileView.as_view()),
]

django_journal/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static


urlpatterns = [
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('journal/', include('journal.urls')),
    path('mailing/', include('mailing.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/', include('api.v1.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

people/urls.py
from django.urls import path

from people.views import TeacherListView, TeacherDetailView, StudentDetailView, StudentLkDetailView, \
    StudentUpdateView, StudentCreateView


urlpatterns = [
    path('teacher/', TeacherListView.as_view(), name='teacher_list'),
    path('teacher/info/<int:pk>/', TeacherDetailView.as_view(), name='teacher_detail'),
    path('student/add/', StudentCreateView.as_view(), name='student_add'),
    path('student/update/<int:pk>/', StudentUpdateView.as_view(), name='student_update'),
    path('student/info/<int:pk>/', StudentDetailView.as_view(), name='student_detail'),
    path('student/', StudentLkDetailView.as_view(), name='student_lk'),
    ]

people/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.urls import reverse_lazy

from django_journal.settings import USER_STATUS_CHOICES, GENDER_CHOICES, STUDY_CHOICES, STUDY_DEGREE_CHOICES, TEACHER


class User(AbstractUser):
    """Користувач."""
    first_name = models.CharField('Ім\'я', max_length=130)
    last_name  = models.CharField('Фамілія', max_length=130)
    middle_name = models.CharField('По-батькові', max_length=130)
    sex = models.CharField('Стать', choices=GENDER_CHOICES, max_length=1)
    birth_date = models.DateField('Дата народження', blank=True, null=True)
    photo = models.ImageField(upload_to='people/', default='static/img/default-user.png', blank=True)
    description = models.TextField('Характеристика')
    user_status = models.CharField('Статус користувача', choices=USER_STATUS_CHOICES, max_length=15)
    updated = models.DateField('Дата оновлення', auto_now=True)


    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    def __str__(self):
        return self.last_name+" "+self.first_name+" "+self.middle_name

    class Meta:
        verbose_name = 'Користувач'
        verbose_name_plural = 'Користувачі'


class Contact(models.Model):
    """Контактні дані студентів, викладачів"""
    phone1 = models.CharField(max_length=12, blank=True, verbose_name='Телефон 1')
    phone2 = models.CharField(max_length=12, blank=True, verbose_name='Телефон 2')
    phone3 = models.CharField(max_length=12, blank=True, verbose_name='Телефон 3')
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='contact', null=True, blank=True,
                                verbose_name='Контактные данные', on_delete=models.CASCADE)

    def __str__(self):
        return self.phone1

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакти'


class Teacher(models.Model):
    """Викладачі"""
    position = models.CharField('Посада', max_length=99)
    group_manager = models.ForeignKey('journal.GroupStudent', related_name='teacher',
                                      on_delete=models.SET_NULL, null=True, blank=True)
    lessons = models.ManyToManyField('journal.Lesson', related_name='teachers', verbose_name='Викладає дисципліни')
    education = models.TextField('Освіта')
    study_work = models.TextField('Навчальна робота')
    science_work = models.TextField('Наукові публікації')
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='teacher', on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse_lazy('teacher_detail', kwargs={'pk': self.user_id})

    class Meta:
        verbose_name = 'Викладач'
        verbose_name_plural = 'Викладачі'


class Student(models.Model):
    """Студенти"""
    study_form = models.CharField('Форма навчання', choices=STUDY_CHOICES, max_length=20)
    study_degree = models.CharField('Ступінь навчання', choices=STUDY_DEGREE_CHOICES, max_length=30)
    entry_year = models.IntegerField('Рік вступу')
    group = models.ForeignKey('journal.GroupStudent', related_name='students', verbose_name='Навчається в групі',
                              on_delete=models.CASCADE)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='student', on_delete=models.CASCADE)
    course_work = models.CharField('Тема курсової роботи', max_length=100)
    course_supervisor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='supervisor', on_delete=models.SET_NULL,
                                null=True, limit_choices_to={'user_status': TEACHER}, verbose_name='Викладач')
    diploma_work = models.CharField('Тема курсової роботи', max_length=100)
    diploma_supervisor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='supervisors',
                                          on_delete=models.SET_NULL,
                                          null=True, limit_choices_to={'user_status': TEACHER}, verbose_name='Викладач')


    def get_absolute_url(self):
        return reverse_lazy('student_detail', kwargs={'pk': self.user_id})

    class Meta:
        verbose_name = 'Студент'
        verbose_name_plural = 'Студенти'

api/v1/people/views.py
from django.core.exceptions import ObjectDoesNotExist
from rest_framework import generics, status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from django.contrib.auth import authenticate
from rest_framework.authtoken.models import Token

from api.v1.people.serializers import UserSerializer, UserTeacherDetailSerializer, UserStudentDetailSerializer, \
    UserStudentCreateSerializer
from api.v1.permissions import IsTeacher, IsTeacherOrOwnerUser
from django_journal.settings import TEACHER, STUDENT
from people.models import User


class TeacherListView(generics.ListAPIView):
    """Виведення усіх викладачів кафедри"""
    queryset = User.objects.filter(user_status=TEACHER)
    serializer_class = UserSerializer


class TeacherProfileView(generics.RetrieveAPIView):
    """Виведення інформації про викладача."""
    queryset = User.objects.filter(user_status=TEACHER)
    serializer_class = UserTeacherDetailSerializer
    permission_classes = (IsAuthenticated, IsTeacher)


class StudentProfileView(generics.RetrieveUpdateAPIView):
    """Оновлення або вивід інформації про студента"""
    queryset = User.objects.filter(user_status=STUDENT)
    serializer_class = UserStudentDetailSerializer
    permission_classes = (IsAuthenticated, IsTeacherOrOwnerUser)


class StudentCreateView(generics.CreateAPIView):
    """Створення студента"""
    queryset = User.objects.all()
    serializer_class = UserStudentCreateSerializer
    permission_classes = (IsAuthenticated, IsTeacher)


class LoginView(APIView):
    """Авторизація користувача"""
    permission_classes = []

    # def post(self, request):
    #     print("Ne lmao")
    #     return Response({'error': 'Wrong Credentials'}, status=status.HTTP_400_BAD_REQUEST)
        # username = request.data.get('username')
        # password = request.data.get('password')
        # user = authenticate(username=username, password=password)
        #
        # if user is None:
        #     return Response({'error': 'Wrong Credentials'}, status=status.HTTP_400_BAD_REQUEST)
        # else:
        #     try:
        #         token = Token.objects.get(user=user)
        #     except ObjectDoesNotExist:
        #         token = Token.objects.create(user=user)
        #     return Response({'Token': str(token)})

people/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Count, Sum, Avg
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView

from django_journal.permissions import TeacherPermissionsMixin, StudentPermissionsMixin
from django_journal.settings import STUDENT, TEACHER
from people.forms import UserCreateForm, StudentForm, ContactForm, ContactFormSet, StudentFormSet, UserUpdateForm
from people.models import Teacher, Student, Contact, User
from journal.models import Lesson, Score
from utils.service import ScoreJournalMixin


class TeacherListView(LoginRequiredMixin, ListView):
    """Список всіх співробітників"""
    template_name = 'people/teacher_list.html'

    def get_queryset(self):
        queryset = User.objects.select_related('teacher__group_manager__grade').filter(user_status=TEACHER)
        return queryset


class TeacherDetailView(LoginRequiredMixin, TeacherPermissionsMixin, DetailView):
    """Виведення інформації про співробітника."""
    model = Teacher
    template_name = 'people/teacher_detail.html'

    def get_queryset(self):
        queryset = User.objects.select_related('teacher__group_manager__grade').filter(user_status=TEACHER)
        return queryset


class StudentDetailView(LoginRequiredMixin, TeacherPermissionsMixin, DetailView):
    """Інформація про студента."""
    template_name = 'people/student_detail.html'

    def get_queryset(self):
        queryset = User.objects.select_related('student__group__grade', 'contact').filter(user_status=STUDENT)
        return queryset


class StudentLkDetailView(LoginRequiredMixin, StudentPermissionsMixin, ScoreJournalMixin, DetailView):
    """Особистий кабінет студента."""
    template_name = 'people/student_lk.html'
    context_object_name = 'student'

    def get_object(self, queryset=None):
        return User.objects.select_related('student', 'contact').get(pk=self.request.user.pk)

    def get_context_data(self, **kwargs):
        context = super(StudentLkDetailView, self).get_context_data(**kwargs)
        date_period = self.create_date_period_list()
        lessons = Lesson.objects.filter(grade__group__students=self.request.user.student.id)
        scores = Score.objects.filter(student_id=self.request.user.pk,
                                      created__in=date_period).values('id', 'lesson_id', 'score', 'created')

        count_scores = scores.values('score').annotate(count_score=Count('score')).order_by('-score')
        total_scores = count_scores.aggregate(sum_count=Sum('count_score'),
                                              sum_score=Avg('score'),
                                              sum_score_percent=Avg('score') * 20)

        student_rating = {100: 0, 99: 0, 98: 0, 97: 0, 96: 0, 95: 0, 94: 0, 93: 0, 92: 0, 91: 0, 90: 0,
                          89: 0, 88: 0, 87: 0, 86: 0, 85: 0, 84: 0, 83: 0, 82: 0, 81: 0, 80: 0, 79: 0, 78: 0,
                          77: 0, 76: 0, 75: 0, 74: 0, 73: 0, 72: 0, 71: 0, 70: 0, 69: 0, 68: 0, 67: 0, 66: 0,
                          65: 0, 64: 0, 63: 0, 62: 0, 61: 0, 60: 0, }
        for item in count_scores:
            student_rating[item['score']] = item['count_score']

        context['rating'] = student_rating
        context['total_scores'] = total_scores
        context['date_period'] = date_period
        context['lessons'] = lessons
        context['scores_dict'] = self.create_scores_dict(date_period, scores, lessons, 'lesson_id')
        return context


class StudentCreateView(LoginRequiredMixin, TeacherPermissionsMixin, SuccessMessageMixin, CreateView):
    """Створення нового студента."""
    form_class = UserCreateForm
    template_name = 'people/student_create.html'
    success_url = reverse_lazy('student_add')
    success_message = 'Студент успішно доданий.'

    def get_context_data(self, **kwargs):
        data = super(StudentCreateView, self).get_context_data(**kwargs)
        data['student_form'] = StudentForm()
        data['contact_form'] = ContactForm()
        return data

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        student_form = StudentForm(self.request.POST)
        contact_form = ContactForm(self.request.POST)
        if form.is_valid() and student_form.is_valid() and contact_form.is_valid():
            user = form.save(commit=False)
            user.user_status = STUDENT
            student = student_form.save(commit=False)
            contact = contact_form.save(commit=False)
            student.user = user
            contact.user = user
            user.save()
            student.save()
            contact.save()
            return self.form_valid(form)
        else:
            messages.error(request, 'Помилка зберігання !')
            return self.render_to_response({'form': form, 'student_form': student_form, 'contact_form': contact_form})


class StudentUpdateView(LoginRequiredMixin, TeacherPermissionsMixin, SuccessMessageMixin, UpdateView):
    """Редагувати профіль студента."""
    model = User
    queryset = User.objects.filter(user_status=STUDENT)
    form_class = UserUpdateForm
    template_name = 'people/student_update.html'
    success_message = 'Дані студента успішно оновлені.'

    def post(self, request, *args, **kwargs):
        form = UserUpdateForm(self.request.POST)
        student_formset = StudentFormSet(self.request.POST, prefix='student')
        contact_formset = ContactFormSet(self.request.POST, prefix='contact')
        if student_formset.is_valid() and contact_formset.is_valid():
            contact_formset.save()
            student_formset.save()
            return super(StudentUpdateView, self).post(self.request.POST)
        else:
            messages.error(request, 'Помилка зберігання !')
            return self.render_to_response(
                {'form': form, 'student_form': student_formset, 'contact_form': contact_formset}
            )

    def get_context_data(self, **kwargs):
        data = super(StudentUpdateView, self).get_context_data(**kwargs)
        student_formset = StudentFormSet(queryset=Student.objects.filter(user_id=self.kwargs['pk']), prefix='student')
        contact_formset = ContactFormSet(queryset=Contact.objects.filter(user_id=self.kwargs['pk']), prefix='contact')

        data['student_form'] = student_formset
        data['contact_form'] = contact_formset
        return data

    def get_success_url(self):
        return reverse_lazy('student_update', kwargs={'pk': self.kwargs['pk']})

people/templates/people/student_create.html
{% extends 'base.html' %}

{% block title %}Новий студент{% endblock %}

{% block content %}
    <h1>Новий студент</h1>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
            {% endfor %}
        </ul>
    {% endif %}

    <form action="" method="post" enctype="multipart/form-data">
        <div class="create-form">
            {% csrf_token %}
            <div id="left-side">
                <p>
                    {{ form.username }}
                    {{ form.username.errors }}
                </p>

                <p>
                    {{ form.email }}
                    {{ form.email.errors }}
                </p>

                <p>
                    {{ form.password }}
                    {{ form.password.errors }}
                </p>

                <p>
                    {{ form.first_name }}
                    {{ form.first_name.errors }}
                </p>
                <p>
                    {{ form.last_name }}
                    {{ form.last_name.errors }}
                </p>

                <p>
                    {{ form.middle_name }}
                    {{ form.middle_name.errors }}
                </p>
                <p>
                    <label for="{{ form.birth_date.id_for_label }}">Дата народження:</label> <br>
                    {{ form.birth_date }}
                    {{ form.birth_date.errors }}
                </p>

                 <p>
                    <label for="{{ form.sex.id_for_label }}">Стать:</label> <br>
                    {{ form.sex }}
                    {{ form.sex.errors }}
                </p>
            </div>

            <div id="right-side">
                <p>
                    {{ form.description }}
                    {{ form.description.errors }}
                </p>
                <p style="color: #606479; font-size: 14px">Фото студента:</p>
                <p>
                    <label class="label-file" for="{{ form.photo.id_for_label }}">Завантажити фото</label> <br>
                    <input type="file" name="photo" class="input-file" accept="image/*" id="id_photo"
                           onchange="document.getElementById('upload-file-info').innerText = this.value;">
                    <br>
                    <span class='label-info' id="upload-file-info"></span>
                    {{ form.photo.errors }}
                </p>
                <p>
                    <label for="{{ student_form.group.id_for_label }}">Студент групи:</label> <br>
                    {{ student_form.group }}
                    {{ student_form.group.errors }}
                </p>
                <p>
                    <label>Форма навчання:</label> <br>
                    {{ student_form.study_form }}
                    {{ student_form.study_form.errors }}
                </p>
                <p>
                    <label>Ступінь навчання:</label> <br>
                    {{ student_form.study_degree }}
                    {{ student_form.study_degree.errors }}
                </p>
                <p>
                    <label>Рік вступу:</label> <br>
                    {{ student_form.entry_year }}
                    {{ student_form.entry_year.errors }}
                </p>
                <p>
                    {{ contact_form.phone1 }}
                    {{ contact_form.phone1.errors }}
                </p>
                <p>
                    {{ contact_form.phone2 }}
                    {{ contact_form.phone2.errors }}
                </p>
                <p>
                    {{ contact_form.phone3 }}
                    {{ contact_form.phone3.errors }}
                </p>
                <p>
                    <label>Тема курсової роботи:</label> <br>
                    {{ student_form.study_degree }}
                    {{ student_form.study_degree.errors }}
                </p>
                <p>
                    <label>Керівник курсової роботи:</label> <br>
                    {{ student_form.course_supervisor }}
                    {{ student_form.course_supervisor.errors }}
                </p>
                <p>
                    <label>Тема кваліфікаційної роботи(бакалавр):</label> <br>
                    {{ student_form.diploma_work }}
                    {{ student_form.diploma_work.errors }}
                </p>
                <p>
                    <label>Керівник кваліфікаційної роботи(бакалавр):</label> <br>
                    {{ student_form.diploma_supervisor }}
                    {{ student_form.diploma_supervisor.errors }}
                </p>
            </div>


            <div id="contact">
                <input type="submit" class="save_button" value="Зберегти">
            </div>

        </div>
    </form>
{% endblock %}

people/templates/people/student_detail.html
{% extends "base.html" %}

{% block title %}Детальна інформація {{ user.get_full_name }}{% endblock %}

{% block content %}
    <h1>Інформація про студента </h1>
    <div class="people-info ">
        <div class="people-photo-block">
            <img class="user-avatar" src="{{ user.photo.url }}" alt="{{ user.get_full_name }}">
        </div>

        <div class="people-info-block">
            <h3>{{ user.get_full_name }}</h3>
            <p><i><u>Дата народження:</u></i> {{ user.birth_date|date:"d.m.Y" }}</p>
            <p><i><u>Група:</u></i> {{ user.student.group.grade }}</p>
            <p><i><u>Форма навчання:</u></i> {{ user.student.study_form }}</p>
            <p><i><u>Ступінь навчання:</u></i> {{ user.student.study_degree }}</p>
            <p><i><u>Рік вступу:</u></i> {{ user.student.entry_year }}</p>
            <span class="small-font">Характеристика</span><hr>
            <p>{{ user.description }}</p>

            {% include "people/include/people_contact_info.html" %}

            <div class="navigaonusing">
                <div class="gaonutosal">
                    <div class="pesontedan">
                        <input id="pesontedan-one" type="checkbox" name="pesontedans">
                        <label for="pesontedan-one">Детальна інформація</label>
                        <div class="pesontedan-content">
                            <p><i><u>Тема курсової роботи:</u></i> {{ user.student.course_work }}</p>
                        </div>
                        <div class="pesontedan-content">
                            <p><i><u>Керівник курсової роботи:</u></i> {{ user.student.course_supervisor }}</p>
                        </div>
                        <div class="pesontedan-content">
                            <p><i><u>Тема кваліфікаційної роботи(бакалавр):</u></i> {{ user.student.diploma_work }}</p>
                        </div>
                        <div class="pesontedan-content">
                            <p><i><u>Керівник кваліфікаційної роботи(бакалавр):</u></i> {{ user.student.diploma_supervisor }}</p>
                        </div>
                    </div>
               </div>
            </div>
        </div>
    </div>
{% endblock %}

people/templates/people/student_lk.html
{% extends 'base.html' %}

{% block title %} Особистий кабінет {% endblock %}

{% block content %}
    <h1>Оцінки</h1>
    <form action="{% url 'student_lk' %}" method="get">
        <label> С
            <input class="input-date" name="start-date" type="date" value="{{ date_period|first|date:"Y-m-d" }}" >
        </label>

        <label> по
            <input class="input-date" name="end-date" type="date" value="{{ date_period|last|date:"Y-m-d" }}">
        </label>
        <button class="btn-filter btn-filter-purple" type="submit">Виконати</button>
    </form>
    <p></p>

    <table class="table-journal">
        <thead>
            <tr>
                <th>Дисципліни</th>
                 {% for date in date_period %}
                     <th>{{ date|date:"d.m.Y" }}</th>
                 {% endfor %}
            </tr>
        </thead>

        <tbody>
        {% for lesson in lessons %}
            <tr>
                <td>{{ lesson.name }}</td>
                {% for date in date_period %}
                    {% with score_id_tuple=scores_dict|get_dict_value:date|get_dict_value:lesson.id %}
                        <td>
                            {% if score_id_tuple|get_list_value:0 == 0 %}
                                <span data-scoreid="{{ score_id_tuple|get_list_value:1 }}">--</span>
                            {% else %}
                                <span data-scoreid="{{ score_id_tuple|get_list_value:1 }}">
                                    {{ score_id_tuple|get_list_value:0 }}
                                </span>
                            {% endif %}

                        </td>
                    {% endwith %}
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <p></p>
    {% include "people/include/people_rating_bar.html" %}
    {% include "people/include/people_contact_info.html" %}

{% endblock %}

people/templates/people/student_update.html
{% extends 'base.html' %}

{% block title %}Редагувати профіль студента{% endblock %}

{% block content %}
    <h1>Редагувати профіль студента</h1>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
            {% endfor %}
        </ul>
    {% endif %}

     <form action="" method="post" enctype="multipart/form-data">
        <div class="create-form">
            {% csrf_token %}

            <div id="left-side">

               <p>
                    <label for="{{ form.first_name.id_for_label }}">Ім'я:</label> <br>
                    {{ form.first_name }}
                    {{ form.first_name.errors }}
                </p>
                <p>
                    <label for="{{ form.last_name.id_for_label }}">Прізвище:</label> <br>
                    {{ form.last_name }}
                    {{ form.last_name.errors }}
                </p>

                <p>
                    <label for="{{ form.middle_name.id_for_label }}">По-батькові:</label> <br>
                    {{ form.middle_name }}
                    {{ form.middle_name.errors }}
                </p>
                <p>
                    <label for="{{ form.birth_date.id_for_label }}">Дата народження:</label> <br>
                    {{ form.birth_date }}
                    {{ form.birth_date.errors }}
                </p>

                 <p>
                    <label for="{{ form.sex.id_for_label }}">Стать:</label> <br>
                    {{ form.sex }}
                    {{ form.sex.errors }}
                </p>

                {{ student_form.management_form }}
                {{ student_form.as_p }}
            </div>

            <div id="right-side">
                <p>
                    <label for="{{ form.description.id_for_label }}">Характеристика:</label> <br>
                    {{ form.description }}
                    {{ form.description.errors }}
                </p>

                <p style="color: #606479; font-size: 14px">Фото студента:</p>
                <p>
                    <img id="avatar" align="left" class="user-avatar-mini" src="/media/{{ form.photo.value }}" alt="">
                    <label class="label-file" for="{{ form.photo.id_for_label }}">Завантажити фото</label> <br>
                    <input type="file" name="photo" class="input-file" accept="image/*" id="id_photo"
                           onchange="document.getElementById('upload-file-info').innerText = this.value;
                           document.getElementById('avatar').src = '';">
                    <br>
                    <span class='label-info' id="upload-file-info">Поточне фото: {{ form.photo.value }}</span>
                    {{ form.photo.errors }}
                </p>

                {{ contact_form.as_p }}
            </div>

            <div id="contact">
                <input type="submit" class="save_button" value="Зберегти">
            </div>

        </div>
    </form>
{% endblock %}

people/templates/people/teacher_detail.html
{% extends "base.html" %}

{% block title %}{{ teacher.position }} {{ teacher.family }} {{ teacher.name }}{% endblock %}

{% block content %}
    <h1>Інформація про співробітника</h1>
    <div class="people-info ">
        <div class="people-photo-block">
             <img class="user-avatar" src="{{ user.photo.url }}" alt="{{ user.last_name }} {{ user.first_name }}">
        </div>

        <div class="people-info-block">
            <h3>{{ user.last_name }} {{ user.first_name }} {{ user.middle_name }}</h3>
            <p><i><u>Дата народження:</u></i> {{ user.birth_date|date:"d.m.Y" }}</p>
            <p><i><u>Посада:</u></i> {{ user.teacher.position }} </p>
             {% include "people/include/people_contact_info.html" %}


            <span class="small-font">Освіта</span><hr>
            <p>{{ user.teacher.education|linebreaks }}</p>
            <span class="small-font">Навчальна робота</span><hr>
            <p>{{ user.teacher.study_work|linebreaks }}</p>
            <span class="small-font">Наукові публікації</span><hr>
            <p>{{ user.teacher.science_work|linebreaks }}</p>



        </div>
    </div>
{% endblock %}

people/templates/people/teacher_list.html
{% extends "base.html" %}

{% block title %}Список співробітників{% endblock %}

{% block content %}
    <h1>Співробітики</h1>
    <table class="table-journal">
        <thead>
            <tr>
                <th>№</th>
                <th>Фото</th>
                <th>ПІБ</th>
                <th>Посада</th>
            </tr>
        </thead>
        <tbody>
            {% for user in user_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><img class="user-avatar-mini" src="{{ user.photo.url }}" alt=""></td>
                    <td>
                        <a href="{{ user.teacher.get_absolute_url }}">
                            {{ user.get_full_name }}
                        </a>
                    </td>
                    <td>{{ user.teacher.position }}</td>
                </tr>
            {% endfor %}

        </tbody>
    </table>
{% endblock %}